----SUPERSTORE SALES ANALYSIS
--Dataset: Superstore Sales Dataset


CREATE DATABASE SUPERSTORE;
GO

USE SUPERSTORE;

CREATE TABLE SUPERSTORE(
ROW_ID INT NOT NULL PRIMARY KEY,
ORDER_ID VARCHAR(50),
ORDER_DATE DATE,
SHIP_ORDER DATE,
SHIP_MODE VARCHAR(50),
CUSTOMER_ID VARCHAR(50),
CUSTOMER_NAME VARCHAR(100),
SEGMENT VARCHAR(50),
COUNTRY VARCHAR(50),
CITY VARCHAR(50),
STATES VARCHAR(50),
POSTAL_CODE VARCHAR(50),
REGION VARCHAR(50),
PRODUCT_ID VARCHAR(50),
CATEGORY VARCHAR(50),
SUB_CATEGORY VARCHAR(50),
PRODUCT_NAME VARCHAR(250),
SALES DECIMAL(12,2)
);



---DATA IMPORT: Download the CSV dataset and replace YOUR_FILE_PATH with the location where the file is saved on your computer

BULK INSERT Superstore
FROM 'YOUR_FILE_PATH\superstore sales dataset.csv'
WITH
(
    FORMAT = 'CSV',
    FIRSTROW = 2,
    FIELDQUOTE = '"',
    FIELDTERMINATOR = ',',
    ROWTERMINATOR = '0x0A',
    CODEPAGE = '65001'
);


---PERFORMING CONSISTENCY CHECK
SELECT COUNT(*) AS TotalRows FROM SUPERSTORE

SELECT TOP 10 * FROM SUPERSTORE

SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'SUPERSTORE';

SELECT COUNT(*) AS TotalCustomers FROM (
  SELECT DISTINCT CUSTOMER_ID 
  FROM SUPERSTORE)
  AS CUSTOMERS;

 SELECT SUM(SALES) AS TotalSales FROM SUPERSTORE;

 SELECT COUNT(DISTINCT ORDER_ID) AS TotalOrder FROM SUPERSTORE;

  SELECT
  COUNT(*) AS TotalRows,
    COUNT (ORDER_ID) AS ORDERID,
    COUNT (ORDER_DATE) AS ORDERDATE,
    COUNT (SHIP_ORDER) AS SHIPORDER,
    COUNT (SHIP_MODE) AS SHIPMODE,
    COUNT (CUSTOMER_ID) AS CUSTOMERID,
    COUNT (CUSTOMER_NAME) AS CUSTOMERNAME,
    COUNT (SEGMENT) AS SEGMENT,
    COUNT (COUNTRY) AS COUNTRY,
    COUNT (CITY) AS CITY,
    COUNT (STATES) AS STATES,
    COUNT (POSTAL_CODE) AS POSTALCODE,
    COUNT (REGION) AS REGION,
    COUNT (PRODUCT_ID) AS PRODUCTID,
    COUNT (CATEGORY) AS CATEGORY,
    COUNT (SUB_CATEGORY) AS SUBCATEGORY,
    COUNT (PRODUCT_NAME) AS PRODUCTNAME,
    COUNT (SALES) AS SALES
FROM SUPERSTORE;


---SALES BY CATEGORY
SELECT CATEGORY, SUM(SALES) AS TotalSales 
  FROM SUPERSTORE
  GROUP BY CATEGORY
  ORDER BY TotalSales DESC;


  ---SALES BY  CUSTOMER REGION
SELECT REGION, SUM(SALES) AS TotalSales
  FROM SUPERSTORE
  GROUP BY REGION
  ORDER BY TotalSales DESC;


  ---TOP 10 PRODUCT WITH THE HIGHEST SALES
  SELECT TOP 10 (PRODUCT_NAME),SUM(SALES)AS TotalSales
  FROM SUPERSTORE
  GROUP BY PRODUCT_NAME
  ORDER BY TotalSales DESC;


  --- TOTAL YEARLY SALES
  SELECT YEAR (ORDER_DATE) AS YEAR, SUM(SALES) AS TotalSales
  FROM SUPERSTORE
  GROUP BY YEAR (ORDER_DATE)
  ORDER BY YEAR;


  ---SALES BY CUSTOMER SEGMENT
  SELECT SEGMENT, SUM(SALES) AS TotalSales
  FROM SUPERSTORE
  GROUP BY SEGMENT
  ORDER BY TotalSales;


  ---SALES BY SUB-CATEGORY
  SELECT SUB_CATEGORY, SUM(SALES) AS TotalSales
  FROM SUPERSTORE
  GROUP BY SUB_CATEGORY
  ORDER BY TotalSales DESC;


  --- TOP 10 CUSTOMER WITH THE HIGHEST SALES
  SELECT TOP 10 (CUSTOMER_NAME), SUM(SALES) AS TotalSales
  FROM SUPERSTORE
  GROUP BY CUSTOMER_NAME
  ORDER BY TotalSales DESC;


  ---SALES BY SHIP MODE
  SELECT SHIP_MODE, SUM(SALES) AS TotalSales
  FROM SUPERSTORE
  GROUP BY SHIP_MODE
  ORDER BY TotalSales DESC;


  ---COMPARING SALES BY CATEGORY AND REGION
  SELECT REGION,CATEGORY, SUM(SALES) AS TotalSales
  FROM SUPERSTORE
  GROUP BY REGION, CATEGORY
  ORDER BY REGION, TotalSales DESC;

  ---STATE WITH SALES ABOVE AVERAGE
  SELECT STATES, SUM(SALES) AS TotalSales
  FROM SUPERSTORE
  GROUP BY STATES
  HAVING SUM(SALES) > (
     SELECT AVG(SALES)
     FROM SUPERSTORE )
     ORDER BY TotalSales DESC;


---RANK PRODUCTS BY TOTAL SALES
SELECT PRODUCT_NAME, SUM(SALES) AS TotalSales,
 RANK() OVER (ORDER BY SUM(SALES) DESC) AS SalesRank
FROM SUPERSTORE
GROUP BY PRODUCT_NAME
ORDER BY SalesRank;


---SALES FOR EACH MONTH OF EVERY YEAR
SELECT YEAR(ORDER_DATE) AS Year,
 MONTH(ORDER_DATE) AS Month,
 SUM(SALES) AS TotalSales
FROM SUPERSTORE
GROUP BY YEAR(ORDER_DATE), MONTH(ORDER_DATE)
ORDER BY Year, Month;


---AVERAGE ORDER 
SELECT SUM(SALES)/ COUNT(DISTINCT ORDER_ID) AS AverageOrder
FROM SUPERSTORE;


---WHICH PRODUCT CATEGORIES GENERATE THE MOST SALES WITHIN EACH CUSTOMER SEGMENT
SELECT SEGMENT, CATEGORY,
 SUM(SALES) AS TotalSales
FROM SUPERSTORE
GROUP BY SEGMENT,CATEGORY
ORDER BY SEGMENT,TotalSales DESC;


---TOP 10 STATES BY SALES
SELECT TOP 10(STATES), SUM(SALES) AS totalSales 
FROM SUPERSTORE
GROUP BY STATES
ORDER BY TotalSales DESC;


---10 PRODUCTS WITH THE LOWEST TOTAL SALES
SELECT TOP 10(PRODUCT_NAME), SUM(SALES) AS TotalSales
FROM SUPERSTORE
GROUP BY PRODUCT_NAME
ORDER BY TotalSales ASC;


---CATEGORY PERCENTAGE OF TOTAL SALES
SELECT CATEGORY, SUM(SALES) AS TotalSales,
 ROUND ( 
 SUM(SALES) * 100 / 
 (SELECT SUM(SALES) FROM SUPERSTORE),2) AS SalesPercentage
FROM SUPERSTORE
GROUP BY CATEGORY
ORDER BY TotalSales DESC;







 








